artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Durgeshsingh12712/Data-All/refs/heads/main/skillscan.zip
  local_data_file: artifacts/data_ingestion/skillscan.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["skillscan.csv", "skillscan.zip"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/skillscan.csv
  tokenizer_name: tfidf
  max_features: 6859

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.pkl
  vectorizer_name: vectorizer.pkl
  label_encoder_name: label_encoder.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json